services:
  # The Backend Service (Node.js Server)
  - type: web
    name: product-recommender-backend
    runtime: node
    rootDir: ./Backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      # Add other secrets like DATABASE_URL, JWT_SECRET etc. here
      # This key below is for your CORS configuration
      - key: FRONTEND_URL
        value: https://product-recommender-frontend.onrender.com

  # The Frontend Service (Vite Static Site)
<<<<<<< HEAD
  - type: static Site
=======
  - type: static site
>>>>>>> 041e75d95c0dc1b137e2001485a617eb0c695ab0
    name: product-recommender-frontend
    rootDir: ./product-recommender
    buildCommand: npm install && npm run build
    publishDir: ./dist  # 'dist' is the default output for Vite
    routes:
      # Rewrite rule to forward API requests to the backend
      - type: rewrite
        source: /api/*
        destination: https://product-recommender-backend.onrender.com/api/*
